export const PERMISSIONS = {
    CREATE_USER: "CREATE_USER",
    UPDATE_USER: "UPDATE_USER",
    DELETE_USER: "DELETE_USER",
    VIEW_USER: "VIEW_USER",
    CREATE_ROLE: "CREATE_ROLE",
    UPDATE_ROLE: "UPDATE_ROLE",
    DELETE_ROLE: "DELETE_ROLE",
    VIEW_ROLE: "VIEW_ROLE",
    ASSIGN_PERMISSION: "ASSIGN_PERMISSION",
  };